alias ls="ls --color"
alias ll="ls -l"
#export G4BLSYS="/home/dorothea/MC/G4Beamline/G4beamline-2.14/bin"
export ROOTSYS="/home/pienu/packages/root"
#export ROOTSYS="/home/dorothea/Root/root"
export MIDASSYS="/home/pienu/packages/midas"
export JAVASYS="/usr/share/xml"
export CMAKESYS="/home/dorothea/.cmake/cmake-2.8.11.1"
export PATH="$ROOTSYS/bin:$MIDASSYS:$JAVASYS:$CMAKESYS/bin:$PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$PYTHONDIR/lib:/home/luca/Analysis/Offline/log4cpp/lib:$LD_LIBRARY_PATH"
#LD_LIBRARY_PATH="/home/luca/Analysis/Offline/log4cpp/lib"
export PYTHONPATH="$ROOTSYS/lib:$PYTHONPATH"
    
