#  To suppress the instantiation of vis manager (G4VisExecutive), by
#  setting G4VIS_NONE, recompile pienu.cc and ensure drawing code is
#  executed only if G4VVisManager::GetConcreteInstance() is non-zero.
#

#/decay/Pienu 1
/decay/Pimunu 1

/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/event/printModulo 1
/rndm/autoSeed true

#Commands for the pileup
/pileup/Active 0
/pileup/Rate 80000
/pileup/Tmin -20000
/pileup/Tmax 5000

#Commands for the beam simulation: 1 from beam,
/beam/FromData 0

#Number of events to simulate
##/run/beamOn 100000
/run/beamOn 100
